name = "HerbstSpringer"
uuid = "d3749c3f-09f0-45e0-93f5-052381da2c19"
authors = ["josephsdavid <josephsd@smu.edu>"]
version = "0.1.0"

[deps]

[extras]
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"

[targets]
test=["ReTest"]
build=["PackageCompiler"]
